// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD9TZvRSai8Vtu3Ld2ehYSyucP1wyzohQ',
    appId: '1:346465594410:web:4b5b38f91db6bcf6ad2753',
    messagingSenderId: '346465594410',
    projectId: 'rent-tech-f5496',
    authDomain: 'rent-tech-f5496.firebaseapp.com',
    storageBucket: 'rent-tech-f5496.firebasestorage.app',
    measurementId: 'G-180MNCXWVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6S8pjLBt_mWgsbXRDqLxAFySbD90ddk',
    appId: '1:346465594410:android:8398e4261b0eb875ad2753',
    messagingSenderId: '346465594410',
    projectId: 'rent-tech-f5496',
    storageBucket: 'rent-tech-f5496.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANbU0sLkIcFifhVJPjDuOEm1kM22o1bdo',
    appId: '1:346465594410:ios:5c068ed412004125ad2753',
    messagingSenderId: '346465594410',
    projectId: 'rent-tech-f5496',
    storageBucket: 'rent-tech-f5496.firebasestorage.app',
    iosBundleId: 'com.renttech.renttech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANbU0sLkIcFifhVJPjDuOEm1kM22o1bdo',
    appId: '1:346465594410:ios:5c068ed412004125ad2753',
    messagingSenderId: '346465594410',
    projectId: 'rent-tech-f5496',
    storageBucket: 'rent-tech-f5496.firebasestorage.app',
    iosBundleId: 'com.renttech.renttech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD9TZvRSai8Vtu3Ld2ehYSyucP1wyzohQ',
    appId: '1:346465594410:web:cc14cc533fa5632dad2753',
    messagingSenderId: '346465594410',
    projectId: 'rent-tech-f5496',
    authDomain: 'rent-tech-f5496.firebaseapp.com',
    storageBucket: 'rent-tech-f5496.firebasestorage.app',
    measurementId: 'G-HRZTMXQ8N6',
  );
}
